=== mikestahelena/kafka-test/src/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "restaurant": {
      "type": "string"
    },
    "customer": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "total_value": {
      "type": "number"
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "item": {
            "type": "integer"
          },
          "dish": {
            "type": "string"
          },
          "spices": {
            "type": "string"
          },
          "vegetable": {
            "type": "string"
          },
          "fruit": {
            "type": "string"
          },
          "drink": {
            "type": "string"
          },
          "price": {
            "type": "string"
          },
          "quantity": {
            "type": "integer"
          },
          "total": {
            "type": "string"
          }
        }
      }
    },
    "payment_method": {
      "type": "string"
    },
    "updated_at": {
      "type": "string"
    },
    "status_code": {
      "type": "integer"
    },
    "lucky_cookie": {
      "type": "string"
    }
  }
}

=== mikestahelena/kafka-test/src/sample.json
{
  "id": "e581d976-b2f9-4d8d-9340-65baad4f33be",
  "restaurant": "43.499.665/2594-24",
  "customer": "178.903.878-22",
  "state": "RJ",
  "total_value": 327.95,
  "items": [
    {
      "item": 1,
      "dish": "Cachorro Quente Ao Molho",
      "spices": "Especiaria",
      "vegetable": "Catalônia",
      "fruit": "Pêra",
      "drink": "Magna",
      "price": "R$63.61",
      "quantity": 2,
      "total": "R$127.22"
    },
    {
      "item": 2,
      "dish": "Paleta De Carneiro",
      "spices": "Alho",
      "vegetable": "couve-rábano",
      "fruit": "Mirtilo",
      "drink": "Imperial",
      "price": "R$87.75",
      "quantity": 1,
      "total": "R$87.75"
    },
    {
      "item": 3,
      "dish": "Purê De Batata",
      "spices": "Pimenta-do-reino",
      "vegetable": "Pepino",
      "fruit": "Amoras",
      "drink": "Coral",
      "price": "R$12.84",
      "quantity": 1,
      "total": "R$12.84"
    },
    {
      "item": 4,
      "dish": "Açaí",
      "spices": "Canela",
      "vegetable": "Semente de lótus",
      "fruit": "Medronheiro",
      "drink": "Magna",
      "price": "R$33.38",
      "quantity": 3,
      "total": "R$100.14"
    }
  ],
  "payment_method": "money",
  "updated_at": "2022-10-27T22:44:57.764718",
  "status_code": 4169,
  "lucky_cookie": "O prazer de concretizar seus projetos com toda a tranquilidade"
}
